---
- name: install nginx repository
  become: yes
  yum:
    name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm

- name: install nginx
  become: yes
  yum:
    name: nginx

- name: start nginx
  become: yes
  service:
    name: nginx
    state: started

- name: copy nginx.conf
  become: yes
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: reload nginx

- name: copy {{ application.name }}.conf
  become: yes
  become_method: sudo
  template:
    src: "{{ application.name }}.conf"
    dest: /etc/nginx/conf.d/{{ application.name }}.conf
  notify: reload nginx

- name: remove default.conf
  become: yes
  become_method: sudo
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: reload nginx
